import { sqliteTable, text, integer, real, index, uniqueIndex, primaryKey } from "drizzle-orm/sqlite-core";

const revision = () => ({ version: integer().notNull().default(1), createdAt: integer().notNull(), updatedAt: integer().notNull(), updatedByUserId: text().notNull() });
export const users = sqliteTable("users", {
  id: text().primaryKey(), name: text().notNull(), email: text().notNull().unique(), emailVerified: integer({ mode: "boolean" }).notNull().default(false), image: text(),
  createdAt: integer({ mode: "timestamp_ms" }).notNull(), updatedAt: integer({ mode: "timestamp_ms" }).notNull(),
});
export const sessions = sqliteTable("sessions", {
  id: text().primaryKey(), expiresAt: integer({ mode: "timestamp_ms" }).notNull(), token: text().notNull().unique(), createdAt: integer({ mode: "timestamp_ms" }).notNull(), updatedAt: integer({ mode: "timestamp_ms" }).notNull(), ipAddress: text(), userAgent: text(), userId: text().notNull().references(() => users.id, { onDelete: "cascade" }),
});
export const accounts = sqliteTable("accounts", {
  id: text().primaryKey(), accountId: text().notNull(), providerId: text().notNull(), userId: text().notNull().references(() => users.id, { onDelete: "cascade" }), accessToken: text(), refreshToken: text(), idToken: text(), accessTokenExpiresAt: integer({ mode: "timestamp_ms" }), refreshTokenExpiresAt: integer({ mode: "timestamp_ms" }), scope: text(), password: text(), createdAt: integer({ mode: "timestamp_ms" }).notNull(), updatedAt: integer({ mode: "timestamp_ms" }).notNull(),
});
export const verifications = sqliteTable("verifications", { id: text().primaryKey(), identifier: text().notNull(), value: text().notNull(), expiresAt: integer({ mode: "timestamp_ms" }).notNull(), createdAt: integer({ mode: "timestamp_ms" }).notNull(), updatedAt: integer({ mode: "timestamp_ms" }).notNull() });

export const trips = sqliteTable("trips", { id: text().primaryKey(), title: text().notNull(), startDate: text(), endDate: text(), timezone: text().notNull().default("Asia/Shanghai"), baseCurrency: text().notNull().default("CNY"), baseCurrencyLockedAt: integer(), ...revision() });
export const members = sqliteTable("trip_members", { tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), userId: text().notNull().references(() => users.id), role: text({ enum: ["owner", "editor", "viewer"] }).notNull(), status: text({ enum: ["active", "inactive"] }).notNull().default("active"), joinedAt: integer().notNull(), version: integer().notNull().default(1) }, t => [primaryKey({ columns: [t.tripId, t.userId] })]);
export const participants = sqliteTable("trip_participants", { id: text().primaryKey(), tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), name: text().notNull(), userId: text().references(() => users.id), status: text({ enum: ["active", "inactive"] }).notNull().default("active"), ...revision() }, t => [uniqueIndex("participants_user").on(t.tripId, t.userId)]);
export const invites = sqliteTable("trip_invites", { id: text().primaryKey(), tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), tokenHash: text().notNull().unique(), role: text({ enum: ["editor", "viewer"] }).notNull(), participantId: text().references(() => participants.id), expiresAt: integer().notNull(), maxUses: integer().notNull(), usedCount: integer().notNull().default(0), revokedAt: integer(), createdByUserId: text().notNull().references(() => users.id), createdAt: integer().notNull(), version: integer().notNull().default(1) });
export const days = sqliteTable("days", { id: text().primaryKey(), tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), date: text(), title: text().notNull(), position: integer().notNull(), startMinutes: integer().notNull().default(480), ...revision() }, t => [index("days_order").on(t.tripId, t.position)]);
export const items = sqliteTable("day_items", { id: text().primaryKey(), dayId: text().notNull().references(() => days.id, { onDelete: "cascade" }), type: text({ enum: ["place", "event", "hotel", "transport", "border", "note"] }).notNull(), position: integer().notNull(), title: text().notNull(), description: text(), amapPoiId: text(), address: text(), lat: real(), lng: real(), startMinutes: integer(), endMinutes: integer(), stayMinutes: integer().notNull().default(0), fixedTime: integer({ mode: "boolean" }).notNull().default(false), notes: text(), ...revision() }, t => [index("items_order").on(t.dayId, t.position)]);
export const legs = sqliteTable("travel_legs", { id: text().primaryKey(), dayId: text().notNull().references(() => days.id, { onDelete: "cascade" }), fromItemId: text().notNull().references(() => items.id, { onDelete: "cascade" }), toItemId: text().notNull().references(() => items.id, { onDelete: "cascade" }), mode: text({ enum: ["walking", "driving", "cycling", "transit", "manual"] }).notNull().default("transit"), provider: text().notNull().default("amap"), selectedAlternativeId: text(), selectionSource: text().notNull().default("recommended"), manualDurationMinutes: integer(), manualDistanceMeters: integer(), manualDescription: text(), status: text({ enum: ["pending", "ready", "error"] }).notNull().default("pending"), error: text(), requestKey: text(), ...revision() }, t => [index("legs_day").on(t.dayId), uniqueIndex("legs_pair").on(t.dayId, t.fromItemId, t.toItemId)]);
export const alternatives = sqliteTable("route_alternatives", { id: text().primaryKey(), travelLegId: text().notNull().references(() => legs.id, { onDelete: "cascade" }), provider: text().notNull().default("amap"), fingerprint: text().notNull(), position: integer().notNull(), label: text().notNull(), distanceMeters: integer().notNull(), durationSeconds: integer().notNull(), walkingDistanceMeters: integer(), transferCount: integer(), polyline: text({ mode: "json" }).$type<[number, number][]>().notNull(), steps: text({ mode: "json" }).$type<RouteStep[]>().notNull(), summary: text().notNull(), geometryComplete: integer({ mode: "boolean" }).notNull(), fetchedAt: integer().notNull() });
export interface RouteStep { mode: string; instruction: string; distanceMeters?: number; durationSeconds?: number }
export const expenses = sqliteTable("expenses", { id: text().primaryKey(), tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), dayId: text().references(() => days.id, { onDelete: "set null" }), dayItemId: text().references(() => items.id, { onDelete: "set null" }), title: text().notNull(), category: text().notNull(), amountMinor: integer().notNull(), currency: text().notNull(), payerParticipantId: text().notNull().references(() => participants.id), exchangeRateToBase: text().notNull(), baseAmountMinor: integer().notNull(), splitMethod: text({ enum: ["equal", "exact", "percentage", "shares"] }).notNull(), splitMeta: text({ mode: "json" }).$type<{ participantId: string; value: string }[]>().notNull(), incurredAt: integer().notNull(), notes: text(), createdByUserId: text().notNull().references(() => users.id), ...revision() }, t => [index("expenses_date").on(t.tripId, t.incurredAt)]);
export const splits = sqliteTable("expense_splits", { id: text().primaryKey(), expenseId: text().notNull().references(() => expenses.id, { onDelete: "cascade" }), participantId: text().notNull().references(() => participants.id), amountMinor: integer().notNull(), baseAmountMinor: integer().notNull(), createdAt: integer().notNull() }, t => [uniqueIndex("split_person").on(t.expenseId, t.participantId)]);
export const settlements = sqliteTable("settlements", { id: text().primaryKey(), tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), fromParticipantId: text().notNull().references(() => participants.id), toParticipantId: text().notNull().references(() => participants.id), amountMinor: integer().notNull(), currency: text().notNull(), exchangeRateToBase: text().notNull(), baseAmountMinor: integer().notNull(), settledAt: integer().notNull(), note: text(), createdByUserId: text().notNull().references(() => users.id), ...revision() });
export const comments = sqliteTable("comments", { id: text().primaryKey(), tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), targetType: text({ enum: ["trip", "day_item", "expense"] }).notNull(), targetId: text().notNull(), authorUserId: text().notNull().references(() => users.id), content: text().notNull(), createdAt: integer().notNull(), updatedAt: integer().notNull() }, t => [index("comments_target").on(t.tripId, t.targetType, t.targetId)]);
export const activity = sqliteTable("activity_logs", { sequence: integer().primaryKey({ autoIncrement: true }), id: text().notNull().unique(), tripId: text().notNull().references(() => trips.id, { onDelete: "cascade" }), actorUserId: text().notNull().references(() => users.id), action: text().notNull(), entityType: text().notNull(), entityId: text(), summary: text().notNull(), createdAt: integer().notNull() }, t => [index("activity_trip").on(t.tripId, t.sequence)]);
